### ISSUE TITLE
Option for prevent_destroy resource "google_iam_workload_identity_pool_provider"

### ISSUE THREAD

**Issue by tordsta** [SudharsaneSivamany/terraform-google-workload-identity-federation-multi-provider#1]
So the problem i ran into with this module is when running "terraform apply", then "terraform destroy", then "terraform apply" again. This error appers: 

> "Error: Error creating WorkloadIdentityPool: googleapi: Error 409: Requested entity already exists"

This is because "terraform destroy" only soft deletes the resource. And it takes 30 days for the resource to be deleted permanently. To my knowledge there is no way to permanently delete it manually ether. 

This leads to the state in terraform being different to the GCP state. The only way i found to fix it is to rename the pool.
It would be nice if the default (or optional) behaviour on destroy would be to deny the deletion of the resource "google_iam_workload_identity_pool_provider", using prevent_destroy. 

This maintains the correct state in terraform, and forces manual handling of the resource.

**Comment by SudharsaneSivamany** [comment]
Appreciation to @tordsta  for raising this issue!!!

Prevent_destroy lifecycle block is a good option , but needs change of variable flag whenever the resource has to be destroy.
As of now, renaming the pool and provider name will fix this.

As a future scope, I'll  test and try to implement the random resource integer as a suffix for the pool and provider name.
